#!/bin/bash
# /home/vscode/bin/serve
# Patrick McLeam <github@psmware.ie>
### BEGIN INIT INFO
# Description:       Controls my UI/API/Docs servers for the project
### END INIT INFO

DESC="Python/Node Development Servers"
NAME=serve
SCRIPTNAME=/home/vscode/bin/$NAME

case "$1" in
  api)
    cd /app/api
    python manage.py runserver 0.0.0.0:5000
    ;;
  docs)
    cd /app/
    /home/vscode/.local/bin/mkdocs serve -a 0.0.0.0:8000
    ;;
  ui)
    cd /app/ui
    npm start
    ;;
  *)
    echo "Usage: $SCRIPTNAME {api|ui|docs}" >&2
    exit 3
    ;;
esac

exit 0

